hkis/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.conf import settings
from django.urls import path, include
from website.api import router
from website.views import (
    ExerciseListView,
    ExerciseView,
    ProfileView,
    SolutionView,
    StatsDetailView,
    StatsListView,
    about,
    helppage,
    dashboard_view,
    index,
    team,
)


favicon_view = lambda request: redirect("/static/favicon.ico", permanent=True)

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("help/", helppage, name="help"),
    path("team/", team, name="team"),
    path("admin/", admin.site.urls),
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("registration.backends.simple.urls")),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("exercises/", ExerciseListView.as_view(), name="exercises"),
    path("exercises/<slug:slug>", ExerciseView.as_view(), name="exercise"),
    path("exercises/<slug:slug>/solutions", SolutionView.as_view(), name="solutions"),
    path("favicon.ico", favicon_view),
    path("profile/<int:pk>", ProfileView.as_view(), name="profile"),
    path("stats/", StatsListView.as_view(), name="stats"),
    path("stats/<int:pk>", StatsDetailView.as_view(), name="stats"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

website/models.py
import logging
from datetime import timedelta

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Count, IntegerField, Value, Q
from django.db.models.signals import post_save
from django.urls import reverse
from django.utils.text import Truncator
from django.utils.timezone import now
from django.utils import translation
from django_extensions.db.fields import AutoSlugField
from rest_framework import serializers

logger = logging.getLogger(__name__)


class ExerciseQuerySet(models.QuerySet):
    def with_global_stats(self):
        return self.annotate(
            tries=Count("answers__user", distinct=True),
            successes=Count(
                "answers__user", filter=Q(answers__is_valid=True), distinct=True
            ),
        )

    def with_user_stats(self, user):
        if user.is_anonymous:
            return self.annotate(
                user_tries=Value(0, IntegerField()),
                user_successes=Value(0, IntegerField()),
            )
        return self.annotate(
            user_tries=Count("answers", filter=Q(answers__user=user)),
            user_successes=Count(
                "answers",
                filter=Q(answers__user=user) & Q(answers__is_valid=True),
            ),
        )

    def with_weekly_stats(self):
        return self.annotate(
            last_week_tries=Count(
                "answers__user",
                filter=Q(
                    answers__created_at__gt=now() - timedelta(days=7),
                    answers__user__is_staff=False,
                ),
                distinct=True,
            ),
            prev_week_tries=Count(
                "answers__user",
                filter=Q(
                    answers__created_at__gt=now() - timedelta(days=14),
                    answers__created_at__lt=now() - timedelta(days=7),
                    answers__user__is_staff=False,
                ),
                distinct=True,
            ),
            last_week_successes=Count(
                "answers__user",
                filter=Q(
                    answers__is_valid=True,
                    answers__user__is_staff=False,
                    answers__created_at__gt=now() - timedelta(days=7),
                ),
                distinct=True,
            ),
            prev_week_successes=Count(
                "answers__user",
                filter=Q(
                    answers__is_valid=True,
                    answers__user__is_staff=False,
                    answers__created_at__gt=now() - timedelta(days=14),
                    answers__created_at__lt=now() - timedelta(days=7),
                ),
                distinct=True,
            ),
        )


class UserStatsQuerySet(models.QuerySet):
    def recompute(self):
        for user in User.objects.all():
            user_stats, _ = UserStats.objects.get_or_create(user=user)
            user_stats.recompute()


class UserStats(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.FloatField(default=0)  # Computed sum of solved exercise positions.
    rank = models.PositiveIntegerField(blank=True, null=True)
    objects = UserStatsQuerySet.as_manager()

    def recompute(self):
        self.points = sum(
            exercise.position
            for exercise in Exercise.objects.with_user_stats(user=self.user)
            if exercise.user_successes
        )
        self.save()
        self.rank = UserStats.objects.filter(points__gt=self.points).count() + 1
        self.save()


class Exercise(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, blank=True)
    slug = AutoSlugField(populate_from=["title"], editable=True)
    check = models.TextField()
    is_published = models.BooleanField(default=False)
    solution = models.TextField()
    wording = models.TextField()
    initial_solution = models.TextField(blank=True)
    position = models.FloatField(default=0)
    objects = ExerciseQuerySet.as_manager()

    def clean_fields(self, exclude=None):
        """Clean windows-style newlines, maybe inserted by Ace editor, or
        other users.
        """
        if "check" not in exclude:
            self.check = self.check.replace("\r\n", "\n")
        if "solution" not in exclude:
            self.solution = self.solution.replace("\r\n", "\n")
        if "wording" not in exclude:
            self.wording = self.wording.replace("\r\n", "\n")

    class Meta:
        ordering = ["position"]

    def get_absolute_url(self):
        return reverse("exercise", args=[self.slug])

    def __str__(self):
        return self.title


class Snippet(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, editable=False, blank=True, null=True
    )
    source_code = models.TextField()
    output = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    executed_at = models.DateTimeField(blank=True, null=True)

    def short_input(self):
        return self.source_code.split("\n")[:1][:100]

    def short_output(self):
        return self.output.split("\n")[:1][:100]


class Answer(models.Model):
    exercise = models.ForeignKey(
        Exercise, on_delete=models.CASCADE, related_name="answers"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    source_code = models.TextField()
    is_corrected = models.BooleanField(default=False)
    is_valid = models.BooleanField(default=False)
    is_shared = models.BooleanField(default=False)
    correction_message = models.TextField(default="", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    corrected_at = models.DateTimeField(blank=True, null=True)

    def short_correction_message(self):
        return self.correction_message.strip().split("\n")[:1][:100]

    def __str__(self):
        return "{} on {}".format(
            Truncator(self.user.username).chars(30), self.exercise.title
        )

    def get_absolute_url(self):
        return reverse("exercise", args=[self.exercise.slug])


class AnswerSerializer(serializers.ModelSerializer):
    class Meta:
        model = Answer
        fields = "__all__"


class SnippetSerializer(serializers.ModelSerializer):
    class Meta:
        model = Snippet
        fields = "__all__"


def cb_new_answer(sender, instance, created, **kwargs):
    group = f"user.{instance.user.id}.ex.{instance.exercise.id}"
    message = AnswerSerializer(instance).data
    if instance.is_valid:
        user_stats, _ = UserStats.objects.get_or_create(user=instance.user)
        user_stats.recompute()
        message["user_rank"] = user_stats.rank
    channel_layer = get_channel_layer()
    message["type"] = "answer.update"
    logger.info("New answer notification for user %s", instance.user.id)
    async_to_sync(channel_layer.group_send)(group, message)


post_save.connect(cb_new_answer, sender=Answer)

website/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django_ace import AceWidget
from registration.forms import RegistrationForm
from website.models import Answer


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["source_code", "exercise"]
        widgets = {
            "source_code": AceWidget(
                mode="python",
                theme="twilight",
                width="100%",
                height="400px",
                fontsize="16px",
                toolbar=False,
            ),
            "exercise": forms.HiddenInput(),
        }


class HkisRegistrationForm(RegistrationForm):
    email = forms.EmailField(label=_("E-mail (optional)"), required=False)
    field_order = ["username", "password1", "password2", "email"]

website/templates/hkis/about.html
{% extends "hkis/layout.html" %}
{% load hkis_extra %}
{% load i18n static %}
{% block container %}
{% md %}
# {% trans "About Hackinscience" %}

## {% trans "Hackinscience, the online platform" %}

{% url 'team' as team_url %}

{% blocktrans %}The Hackinscience platform is a free, without ads, and open-source
(<a href="http://framagit.org/hackinscience/">repo on framagit</a>)
exercise platform, by a [team]({{team_url}}) of Python passionates.{% endblocktrans %}

{% blocktrans %}We only rely on [your donations](https://liberapay.com/JulienPalard) to run
this.{% endblocktrans %}


## {% blocktrans %}You're a teacher?{% endblocktrans %}

{% blocktrans %}If you're a teacher and want to use hackinscience during your courses,
you can ask by email at team at hackinscience dot org for a teacher
account, we'll bind you to your class students so you can follow their
individual progression.{% endblocktrans %}


## {% blocktrans %}You'd like The Hackinscience Team for a class?{% endblocktrans %}

{% blocktrans %}Good news, we teach Python too! Don't hesitate to drop us an email at
team at hackinscience dot org and we'll discuss about it. We're based
in Paris, France, but it may be OK for the team to move in other
places, let's talk about it!{% endblocktrans %}


## {% blocktrans %}Friendly Tracebacks in corrections{% endblocktrans %}

{% blocktrans %}You may have spotted Python exceptions are often nicely explained, how
do we do that?{% endblocktrans %}

{% blocktrans %}We're using André Roberge's
[friendly-traceback](https://github.com/aroberge/friendly-traceback/),
a project which tries to understand what caused the exception, and
explain it.{% endblocktrans %}

{% blocktrans %}If you spot an exception that is not explained by
`friendly-traceback`, which end up with "You might want to report this
case to ...", don't hesitate to report the case to the given link,
André is always very fast to implement the case and it will help many
people, not only hackinscience users!{% endblocktrans %}

{% blocktrans %}In the other hand if you spot a correction message that is not
helpfull and does not give a link to `friendly-traceback`, please open
an issue on [hackinscience](framagit.org/hackinscience/hkis-website)'s
issue tracker, as it's probably to be enhanced in our side.{% endblocktrans %}


## {% blocktrans %}Privacy{% endblocktrans %}

### {% blocktrans %}Personal informations{% endblocktrans %}

{% blocktrans %}When registering and using the Hackinscience platform, we store some
informations about you:{% endblocktrans %}

- {% blocktrans %}Your username, maybe your email if you gave it at registration time.{% endblocktrans %}
- {% blocktrans %}All the exercises you did, when you did them, what you submitted, what the bot answered.{% endblocktrans %}

{% blocktrans %}Why do we store all your submissions?{% endblocktrans %}

- {% blocktrans %}To display ✓ and ✗ marks near exercises so you know which one you
  succeeded and which one to do.{% endblocktrans %}
- {% blocktrans %}So you can find them back tomorrow.{% endblocktrans %}
- {% blocktrans %}Compute some statistics to spot which exercises are too hard to order them better or
  introduce intermediate/easier ones.{% endblocktrans %}

{% blocktrans %}If you want to correct an information we've got about you, delete
it, or if you'd like all the data about you conveniently archived for
offline reading, feel free to send a mail to *team at hackinscience dot org*
or ask any member of [the team]({{ team_url }}).{% endblocktrans %}


### {% blocktrans %}Trackers, external analytics tools, advertising{% endblocktrans %}

{% blocktrans %}We do not use any trackers, nor any advertising network, all our `css`
and `js` are hosted by ourself (no CDN).{% endblocktrans %}

{% blocktrans %}If you read this, you probably don't like being tracked, there's two
complimentary things you can do:{% endblocktrans %}

- {% blocktrans %}Enable the "Do Not Track" flag in your browser{% endblocktrans %}
- {% blocktrans %}Install the [Privacy Badger](https://fr.wikipedia.org/wiki/Privacy_Badger) browser
  extension from the [Electronic Frontier
  Foundation](https://fr.wikipedia.org/wiki/Electronic_Frontier_Foundation).{% endblocktrans %}

{% blocktrans %}Pricavy Badger blocks advertisements and tracking cookies that do not respect the
Do Not Track setting in a user's web browser.{% endblocktrans %}

{% endmd %}
{% endblock %}

website/templates/hkis/base.html
{% load i18n %}{% load static %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>HackInScience - {% block title %}{% trans "Welcome!" %}{% endblock %}</title>
        <link href="{% static "bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "css/hkis.css" %}" rel="stylesheet" type="text/css" />
        {% block stylesheets %}{% endblock %}
        {% block extrastyle %}{% endblock %}
        {% block extrahead %}{% endblock %}
    </head>
    <body id="page-top" class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">
      {% block nav %}
      {% endblock %}
      {% block body %}
      <div class="container-fluid">
        {% block container %}
        {% endblock container %}
      </div>
      {% endblock %}
      <script src="{% static "js/jquery-slim.min.js" %}"></script>
      <script src="{% static "js/util.js" %}"></script>
      <script src="{% static "js/collapse.js" %}"></script>
      {% block extrajs %}
      {% endblock %}
    </body>
</html>

website/templates/hkis/dashboard.html
{% extends "hkis/layout.html" %}

{% block container %}
<h1 class="bd-title">Categories</h1>
<div class="row">
    <div class="col-md-4">
        <h2>{% trans "Python" %}</h2>
        <p>{% trans "Python is a widely used general-purpose, high-level programming language. Its design philosophy emphasizes code readability, and its syntax allows programmers to express concepts in fewer lines of code than would be possible in languages such as C++ or Java..." %}</p>
        <p>
        <a class="btn btn-primary" href="{% url 'exercises' %}" role="button">{% trans "Exercices" %} »</a>
        <a class="btn btn-secondary" href="#" role="button">{% trans "Courses" %} »</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>{% trans "C" %}</h2>
        <p>{% trans "C is a general-purpose, imperative computer programming language, supporting structured programming, lexical variable scope and recursion, while a static type system prevents many unintended operations." %}</p>
        <p>
        <a class="btn btn-secondary disabled" href="#" role="button" aria-disabled="true">{% trans "View details" %} »</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>{% trans "Shell script" %}</h2>
        <p>{% trans "Default Command-line interpreter, for Unix operating systems." %}</p>
        <p>
        <a class="btn btn-secondary disabled" href="#" role="button" aria-disabled="true">{% trans "View details" %} »</a>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>{% trans "Matlab</h2>
        <p>{% trans "MATLAB (matrix laboratory) is a multi-paradigm numerical computing environment and fourth-generation programming language." %}</p>
        <p>
        <a class="btn btn-secondary disabled" href="#" role="button" aria-disabled="true">{% trans "View details" %} »</a>
        </p>
    </div>
</div>
{% endblock %}

website/templates/hkis/exercise.html
{% extends "hkis/layout.html" %}
{% load hkis_extra %}
{% load i18n static %}
{% block title %}
  {% if is_impersonating %}
    {{ object.title }} (as seen by {{ is_impersonating.username }})
  {% else %}
    {{ object.title }}
  {% endif %}
{% endblock %}
{% block stylesheets %}
<link href="{% static "css/codehilite.css" %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block extrahead %}
{% autoescape off %}
{% url 'profile' user.id as profile_url %}
<script>
    function append_to_answer_table(html) {
        if (document.querySelectorAll("#answer-table tr").length)
            document.querySelectorAll("#answer-table tr")[0].insertAdjacentHTML('beforebegin', html);
        else
            document.querySelectorAll("#answer-table")[0].insertAdjacentHTML('afterbegin', html);
    }

    function fill_answer(answer) {
        var result = document.getElementById("answers-result");
        if (!result)
            return;
        var elem = document.getElementById("td-".concat(answer.id));
        if (!elem) {
            var answer_table = document.getElementById("answer-table");
            append_to_answer_table('<tr><td id="td-'.concat(answer.id).concat('">…</td> </tr>'));
            elem = document.getElementById("td-".concat(answer.id));
        }
        if (answer.is_corrected) {
            var div = document.createElement("div");
            var button_next = document.createElement("a")
            button_next.className = 'btn btn-primary btn-sm'
            button_next.innerHTML = '{% trans "Next" %}'
            button_next.href = "{% url "exercise" next %}"

            var button_help = document.createElement("a")
            button_help.innerHTML = '{% trans "Need help?" %}'
            button_help.href = "{% url 'help' %}"

            div.className = "result-box";
            div.innerHTML = answer.correction_message_html;
            if (answer.is_valid) {
                if (answer.user_rank < {{ current_rank }}) {
                    {% if user.is_authenticated %}
                    {% url 'profile' user.id as profile_url %}
                    var message = '<div class="alert alert-success">{% blocktrans %}Your new <a href="{{ profile_url }}">rank</a> is: NEW_RANK{% endblocktrans %}</div>'.replace('NEW_RANK', answer.user_rank);
                    {% else %}
                    var message = '<div class="alert alert-success"></div>';
                    {% endif %}
                    div.insertAdjacentHTML('beforeend', message);
                }
                div.appendChild(button_next);
                document.getElementById("solution_link").removeAttribute("style");
            }
            else {
                div.appendChild(button_help);
            }
            while (elem.firstChild) elem.removeChild(elem.firstChild);
            elem.appendChild(div);
            document.getElementById('submit_answer').removeAttribute('disabled');
        } else {
            elem.innerHTML = '<img src="{% static "img/loading_anim.gif" %}" height=30> {% trans "Waiting for correction" %}';
        }
    }

    function fill_snippet(id, executed_at, output) {
        var result = document.getElementById("answers-result");
        if (!result)
            return;
        var elem = document.getElementById("td-snippet-".concat(id));
        if (!elem) {
            var answer_table = document.getElementById("answer-table");
            append_to_answer_table('<tr><td id="td-snippet-'.concat(id).concat('">…</td> </tr>'));
            elem = document.getElementById("td-snippet-".concat(id));
        }
        if (executed_at) {
            var pre = document.createElement("pre");
            var div = document.createElement("div");
            div.className = "result-box";
            div.appendChild(pre);
            var content = document.createTextNode(output);
            pre.appendChild(content);
            while (elem.firstChild) elem.removeChild(elem.firstChild);
            elem.appendChild(div);
            document.getElementById("submit_snippet").removeAttribute('disabled');
        } else {
            elem.innerHTML = '<img src="{% static "img/loading_anim.gif" %}" height=30> {% trans "Waiting for test run" %}';
        }
    }

    function websocket_connect(ws_location) {
        console.log("Trying to open WebSocket connection.");
        window.ws = new WebSocket(ws_location);
        window.ws.onmessage = function(e) {
            var data = JSON.parse(e.data);
            console.log("WebSocket recv:", data);
            if (data.type == "snippet.update")
                fill_snippet(data.id, data.executed_at, data.output)
            if (data.type == "answer.update")
                fill_answer(data);
        };
        window.ws.onerror = function() {
            console.log("WebSocket error.");
        };
        window.ws.onopen = function() {
            console.log("WebSocket opened.");
            document.querySelectorAll("td.answer-cell").forEach(function(answer) {
                if (answer.dataset.isCorrected == "True") return ;
                console.log("Need to correct answer number", answer.dataset.answerId);
                window.ws.send(JSON.stringify({"type": "recorrect", "id": Number(answer.dataset.answerId)}));
            });
        };
        window.ws.onclose = function() {
            console.log("WebSocket closed, will retry to connect in 5s");
            setTimeout(function(){websocket_connect(ws_location)}, 5000);
        };
    }

    function ws_submit_answer(form) {
        document.getElementById('submit_answer').setAttribute('disabled', true);
        setTimeout(function(){document.getElementById('submit_answer').removeAttribute('disabled');}, 1000);

        var message = {"type": "answer", "source_code": form["source_code"].value};
        console.log("WebSocket send answer", message);
        window.ws.send(JSON.stringify(message));

    }

    function ws_submit_snippet(form) {
        document.getElementById('submit_snippet').setAttribute('disabled', true);
        setTimeout(function(){document.getElementById('submit_snippet').removeAttribute('disabled');}, 1000);

        var message = {"type": "snippet", "source_code": form["source_code"].value};
        console.log("WebSocket send snippet", message);
        window.ws.send(JSON.stringify(message));

    }

    function ctrl_enter_handler(event) {
        if (!event.ctrlKey) return;
        if (event.code !== "Enter") return;
        console.log("Sending via Ctrl-enter");
        ws_submit_answer(document.getElementById("answer_form"));
    }

    var ws_protocol = window.location.protocol == "http:" ? "ws:" : "wss:";
    {% if not is_impersonating %}
    window.addEventListener('DOMContentLoaded', function (event) {
        websocket_connect(ws_protocol + "//" + window.location.host + "/ws/exercises/" + {{object.id}} + "/");
        document.addEventListener('keydown', ctrl_enter_handler);
    });
    {% endif %}
</script>
{% endautoescape %}
{% endblock %}
{% block container %}
{% if is_impersonating %}
  <div class="alert alert-warning" role="alert">
    Exercise as seen by {{ is_impersonating.username }}.
  </div>
{% endif %}
{{ answer_form.media }}
{% if next or previous %}
<div class="float-right">
  {% if previous %}
  <a class="btn btn-secondary" href="{% url "exercise" previous %}">
    ← {% trans "Previous" %}
  </a>
  {% endif %}
  {% if next %}
  <a class="btn btn-secondary" href="{% url "exercise" next %}">
    {% trans "Next" %} →
  </a>
  {% endif %}
</div>
{% endif %}
<div style="margin-bottom: 25px;">
{{ object.wording|markdown_to_bootstrap|i18n_doc_links:LANGUAGE_CODE }}
</div>

<div class="row">
  <div class="col-md-6">
    <h2>{% trans "Your Code" %}</h2>
    <form id="answer_form" action="#" onsubmit="return false;" method="post">{% csrf_token %}
        {% for field in answer_form %}
        <div class="fieldWrapper">
            {{ field }}
        </div>
        {% endfor %}
        {% if not is_impersonating %}
        <button
          id="submit_snippet"
          class="btn btn-secondary"
          data-toggle="tooltip"
          data-placement="bottom"
          data-delay="500"
          title="{% trans "Use this to execute your code, so you can try things." %}"
          onclick="ws_submit_snippet(this.form); return false;">
          {% trans "Run" %}
        </button>
        {% if not user.is_anonymous %}
        <button
          id="submit_answer"
          class="btn btn-primary"
          data-toggle="tooltip"
          data-placement="bottom"
          data-delay="500"
          title="This runs automated tests to verify your implementation (also saves your code).&#013;Shortcut: Ctrl-Enter."
          type="submit"
          onclick="ws_submit_answer(this.form); return false;">
          {% trans "Submit for validation" %}
        </button>
        {% else %}
        <a class="btn btn-primary" href="{% url 'auth_login' %}" role="button">{% trans "Login to check your code and save your progress." %}</a>

        {% endif %}
        {% endif %}
    </form>
  </div>
  <div class="col-md-6">
    <h2>{% trans "Results" %}
      <span id="solution_link" {% if not is_valid %} style="display: none" {% endif %}>
        (<a href={% url "solutions" object.slug %}>{% blocktrans %}{{ solutions_qty}} shared solutions{% endblocktrans %}</a>)
      </span>
    </h2>
    <div id="answers-result" class="result">
      <table id="answer-table" class="table">
        {% for answer in answers %}
        <tr>
          <td id="td-{{ answer.id }}"
              data-answer-id="{{ answer.id }}"
              data-is-corrected="{{ answer.is_corrected }}"
              class="answer-cell">
            {% if not answer.is_corrected %}
              <img src="{% static "img/loading_anim.gif" %}" height=30> {% trans "Waiting for correction" %}
            {% else %}
              <div class="result-box">
              {{ answer.correction_message|markdown_to_bootstrap }}
            </div>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
{% endblock %}

website/templates/hkis/layout.html
{% extends 'hkis/base.html' %}
{% load i18n static %}

{% block nav %}

<nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background: #1e2933; text-transform:uppercase; font-family:Cabin,'Helvetica Neue',Helvetica,Arial,sans-serif; z-index: 100">
  <a class="navbar-brand" href="/">
    <div style="float:left;">
        <img src="{% static "img/logo_hackinscience.png" %}" width="20" height="20" alt="logo"/>
    </div>
    <div style="float:left;margin-left:10px; font-weight: 700">
        HackInScience
    </div>
  </a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'exercises' %}">{% trans "Exercises" %}</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' user.id %}">{% trans "Profile" %}</a>
        </li>
        {% if perms.website.view_answer %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'stats' %}">{% trans "Stats" %}</a>
          </li>
        {% endif %}
        {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
          </li>
        {% endif %}
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'help' %}">{% trans "Help" %}</a>
      </li>
    </ul>
    <ul class="navbar-nav navbar-right">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">{% trans "About" %}</a>
      </li>
      <li class="nav-item">
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'auth_logout' %}">{% trans "Log out" %}</a>
        {% else %}
          <a class="nav-link" href="{% url 'auth_login' %}">{% trans "Sign in" %}</a>
        {% endif %}
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://liberapay.com/JulienPalard">
          <img height="24"
               alt="{% trans "Donate using Liberapay" %}"
               src="{% static "img/liberapay.svg" %}">
        </a>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  <!-- Collect the nav links, forms, and other content for toggling -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
{% endblock %}

website/templates/hkis/stats_list.html
{% extends "hkis/layout.html" %}
{% load i18n %}
{% block title %}Stats{% endblock %}
{% block container %}
<h2>{% trans "Groups" %}</h2>
<ul>
  {% for group in object_list %}
  {% if group.name != "prof" %}
  <li><a href="{% url "stats" group.pk %}">{{ group.name }}</a></li>
  {% endif %}
  {% endfor %}
</ul>
{% endblock %}